spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka:8761/eureka/ # Eureka Server URL
