spring:
  datasource:
    url: jdbc:postgresql://metro_postgresql:5432/userdb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://metro-eureka:8761/eureka/ # Eureka Server URL

server:
  port: 4007
  servlet:
    context-path: /api/${server.servlet.version}
    version: v1

security:
  api:
    key: c761c9f0bb379612afbfd6ffeca90261db961bb93bce17728bc2a74430a66c0a
    header: X-API-KEY
  jwt:
    secret-key: e2bd3b3c7af3861cc4b5eeeeba79892a25739cc44a56eef4c38b92d9b5a39159
    expiration: 3600000 # 1 hour in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

pocketbase:
  url: https://pkb.lch.id.vn
  superuser:
    email: hoangclw@gmail.com
    password: Luucaohoang1604^^