spring:
  application:
    name: station-service

  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:postgresql://metro_postgresql:5432/stationdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 4004

security:
  api:

    key: c761c9f0bb379612afbfd6ffeca90261db961bb93bce17728bc2a74430a66c0a
    header: X-API-KEY
  jwt:
    secret-key: e2bd3b3c7af3861cc4b5eeeeba79892a25739cc44a56eef4c38b92d9b5a39159
    expiration: 3600000 # 1 hour in milliseconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://metro-eureka:8761/eureka/ # Eureka Server URL