spring:
  application:
    name: station-service

  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://eureka:8761/eureka/ # Eureka Server URL

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  api:

    key: c761c9f0bb379612afbfd6ffeca90261db961bb93bce17728bc2a74430a66c0a
    header: X-API-KEY
  jwt:
    secret-key: e2bd3b3c7af3861cc4b5eeeeba79892a25739cc44a56eef4c38b92d9b5a39159
    expiration: 3600000 # 1 hour in milliseconds

server:
  port: 4004