spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieunnse183474@fpt.edu.vn
    password: ynbm jzuo vxsh nphj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/${app.version}
  port: 4008

app:
  version: v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs