version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "4008:4008"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2707
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
